# Generated by Django 2.1 on 2020-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveworld', '0002_saveitem_congratulations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salute', models.TextField()),
            ],
        ),
    ]
